class CollBackData:
    admin_menu = 'admin_menu'
    back_to_main = 'back_to_main'
    clear_course = 'clear_course'
    clear_log = 'clear_log'
    clear_queue = 'clear_queue'
    download_log = 'download_logs'
    get_log = 'get_log'
    get_log_program = 'get_log_program'
    get_registration_webinar = 'get_registration_webinar'
    get_seller = 'get_seller'
    show_queue = 'show_queue'
    zoom_menu = 'zoom_menu'
